Contoso.Apps.SportsLeague/ViewModels/Cart/CartItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Contoso.Apps.SportsLeague.Web.ViewModels
{
    public class CartItemViewModel
    {
        public string ItemId { get; set; }

        public string CartId { get; set; }

        public int Quantity { get; set; }

        public System.DateTime DateCreated { get; set; }

        public int ProductId { get; set; }

        public string ProductProductName { get; set; }

        public string ProductThumbnailPath { get; set; }

        public double? ProductUnitPrice { get; set; }
    }
}

Contoso.Apps.SportsLeague/ViewModels/Store/CartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Contoso.Apps.SportsLeague.Web.ViewModels
{
    public class CartViewModel
    {
        public IList<ViewModels.CartItemViewModel> CartItems { get; set; }
        public decimal OrderTotal { get; set; }
        public int ItemsTotal { get; set; }
    }
}

Contoso.Apps.SportsLeague/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Contoso.Apps.SportsLeague.Data.Models;
using Contoso.Apps.SportsLeague.Web.ViewModels;
using Contoso.Apps.SportsLeague.Data.Logic;
using AutoMapper;
using Contoso.Apps.Common;
using Contoso.Apps.SportsLeague.Web.Helpers;
using System.Threading.Tasks;

namespace Contoso.Apps.SportsLeague.Web.Controllers
{
    public class CheckoutController : Controller
    {
        private ProductContext db = new ProductContext();
        private string cartId = new Helpers.CartHelpers().GetCartId();

        // GET: Checkout
        public ActionResult Index()
        {
            
            var vm = new CheckoutViewModel();
            using (ShoppingCartActions usersShoppingCart = new ShoppingCartActions(cartId))
            {
                var shoppingCartItems = usersShoppingCart.GetCartItems();
                var cartItemsVM = Mapper.Map<List<CartItemViewModel>>(shoppingCartItems);
                vm.CartItems = cartItemsVM;
                vm.OrderTotal = usersShoppingCart.GetTotal();
                vm.ItemsTotal = usersShoppingCart.GetCount();
            }

            // To make filling out the form faster for demo purposes, pre-fill the values:
            vm.Order = new OrderViewModel
            {
                // Important! Keep this property here!
                Total = vm.OrderTotal,
                // Prefill properties for convenience:
                FirstName = "Bob",
                LastName = "Loblaw",
                Address = "1313 Mockingbird Lane",
                City = "Virginia Beach",
                State = "VA",
                PostalCode = "23456",
                Country = "United States",
                Email = "bobloblaw@contososportsleague.com",
                NameOnCard = "Bob Loblaw",
                CreditCardType = "Visa",
                CreditCardNumber = "4111111111111111",
                ExpirationDate = "12/20",
                CCV = "987",
                SMSOptIn = true
            };

            return View(vm);
        }

        // POST: Checkout/Start
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Review(CheckoutViewModel data)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    NVPAPICaller gatewayCaller = new NVPAPICaller();

                    string token = "";
                    NVPCodec decoder = new NVPCodec();

                    // Call the gateway payment authorization API:
                    bool ret = gatewayCaller.DoCheckoutAuth(data.Order, ref token, ref decoder);

                    // If authorizaton is successful:
                    if (ret)
                    {
                        // Hydrate a new Order model from our OrderViewModel.
                        var myOrder = Mapper.Map<Data.Models.Order>(data.Order);
                        // Timestamp with a UTC date.
                        myOrder.OrderDate = DateTime.UtcNow;

                        // Get DB context.
                        ProductContext _db = new ProductContext();

                        // Add order to DB.
                        _db.Orders.Add(myOrder);
                        _db.SaveChanges();

                        // Get the shopping cart items and process them.
                        using (ShoppingCartActions usersShoppingCart = new ShoppingCartActions(cartId))
                        {
                            List<CartItem> myOrderList = usersShoppingCart.GetCartItems();

                            // Add OrderDetail information to the DB for each product purchased.
                            for (int i = 0; i < myOrderList.Count; i++)
                            {
                                // Create a new OrderDetail object.
                                var myOrderDetail = new OrderDetail();
                                myOrderDetail.OrderId = myOrder.OrderId;
                                myOrderDetail.ProductId = myOrderList[i].ProductId;
                                myOrderDetail.Quantity = myOrderList[i].Quantity;
                                myOrderDetail.UnitPrice = myOrderList[i].Product.UnitPrice;

                                // Add OrderDetail to DB.
                                _db.OrderDetails.Add(myOrderDetail);
                                _db.SaveChanges();
                            }

                            // Set OrderId.
                            Session["currentOrderId"] = myOrder.OrderId;
                            Session["Token"] = token;

                            // Report successful event to Application Insights.
                            var eventProperties = new Dictionary<string, string>();
                            eventProperties.Add("CustomerEmail", data.Order.Email);
                            eventProperties.Add("NumberOfItems", myOrderList.Count.ToString());
                            eventProperties.Add("OrderTotal", data.Order.Total.ToString("C2"));
                            eventProperties.Add("OrderId", myOrder.OrderId.ToString());
                            TelemetryHelper.TrackEvent("SuccessfulPaymentAuth", eventProperties);

                            data.Order.OrderId = myOrder.OrderId;
                            if (data.Order.CreditCardNumber.Length > 4)
                            {
                                // Only show the last 4 digits of the credit card number:
                                data.Order.CreditCardNumber = "xxxxxxxxxxx" + data.Order.CreditCardNumber.Substring(data.Order.CreditCardNumber.Length - 4);
                            }
                        }
                    }
                    else
                    {
                        var error = gatewayCaller.PopulateGatewayErrorModel(decoder);

                        // Report failed event to Application Insights.
                        Exception ex = new Exception(error.ToString());
                        ex.Source = "Contoso.Apps.SportsLeague.Web.CheckoutController.cs";
                        TelemetryHelper.TrackException(ex);

                        // Redirect to the checkout error view:
                        return RedirectToAction("Error", error);
                    }
                }
                catch (WebException wex)
                {
                    ExceptionUtility.LogException(wex, "CheckoutController.cs Complete Action");

                    var error = new CheckoutErrorViewModel
                    {
                        ErrorCode = wex.Message
                    };

                    if (wex.Response != null && wex.Response.GetType() == typeof(HttpWebResponse))
                    {
                        // Extract the response body from the WebException's HttpWebResponse:
                        error.LongMessage = ((HttpWebResponse)wex.Response).StatusDescription;
                    }

                    // Redirect to the checkout error view:
                    return RedirectToAction("Error", error);
                }
                catch (Exception ex)
                {
                    ExceptionUtility.LogException(ex, "CheckoutController.cs Review Action");

                    var error = new CheckoutErrorViewModel
                    {
                        ErrorCode = ex.Message
                    };

                    // Redirect to the checkout error view:
                    return RedirectToAction("Error", error);
                }
            }

            return View(data);
        }

        // POST: Checkout/Complete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Complete(OrderViewModel order)
        {
            try
            {
                // TODO: Complete the payment processing via the gateway and update the order...
                NVPAPICaller gatewayCaller = new NVPAPICaller();

                string token = "";
                string finalPaymentAmount = "";
                NVPCodec decoder = new NVPCodec();

                token = Session["token"].ToString();
                //PayerID = Session["payerId"].ToString();
                //finalPaymentAmount = Session["payment_amt"].ToString();
                finalPaymentAmount = order.Total.ToString("C2");

                bool ret = gatewayCaller.DoCheckoutPayment(finalPaymentAmount, token, ref decoder);
                if (ret)
                {
                    // Retrieve PayPal confirmation value.
                    string PaymentConfirmation = decoder[NVPProperties.Properties.TRANSACTIONID].ToString();
                    order.PaymentTransactionId = PaymentConfirmation;


                    ProductContext _db = new ProductContext();
                    // Get the current order id.
                    int currentOrderId = -1;
                    if (Session["currentOrderId"] != null && Session["currentOrderId"].ToString() != string.Empty)
                    {
                        currentOrderId = Convert.ToInt32(Session["currentOrderID"]);
                    }
                    Order myCurrentOrder;
                    if (currentOrderId >= 0)
                    {
                        // Get the order based on order id.
                        myCurrentOrder = _db.Orders.Single(o => o.OrderId == currentOrderId);
                        // Update the order to reflect payment has been completed.
                        myCurrentOrder.PaymentTransactionId = PaymentConfirmation;
                        // Save to DB.
                        _db.SaveChanges();

                        // Queue up a receipt generation request, asynchronously.
                        await new AzureQueueHelper().QueueReceiptRequest(currentOrderId);

Contoso.Apps.SportsLeague/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Contoso.Apps.Common.Extensions;
using Contoso.Apps.SportsLeague.Data.Models;

namespace Contoso.Apps.SportsLeague.Web.Controllers
{
    public class StoreController : Controller
    {
        private ProductContext db = new ProductContext();

        // GET: Store
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Category);
            var productsVm = Mapper.Map<List<ViewModels.ProductListViewModel>>(products);

            // Retrieve category listing:
            var categories = db.Categories.ToList();
            var categoriesVm = Mapper.Map<List<ViewModels.CategoryViewModel>>(categories);

            var vm = new ViewModels.StoreIndexViewModel
            {
                Products = productsVm,
                Categories = categoriesVm
            };

            return View(vm);
        }

        // GET: Store/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            var productVm = Mapper.Map<ViewModels.ProductViewModel>(product);

            // Find related products, based on the category:
            var relatedProducts = db.Products.Where(p => p.CategoryID == product.CategoryID && p.ProductID != product.ProductID).ToList();
            var relatedProductsVm = Mapper.Map<List<ViewModels.ProductListViewModel>>(relatedProducts);

            // Retrieve category listing:
            var categories = db.Categories.ToList();
            var categoriesVm = Mapper.Map<List<ViewModels.CategoryViewModel>>(categories);

            // Retrieve "new products" as a list of three random products not equal to the displayed one:
            var newProducts = db.Products.Where(p => p.ProductID != product.ProductID).ToList().Shuffle().Take(3);

            var newProductsVm = Mapper.Map<List<ViewModels.ProductListViewModel>>(newProducts);

            var vm = new ViewModels.StoreDetailsViewModel
            {
                Product = productVm,
                RelatedProducts = relatedProductsVm,
                NewProducts = newProductsVm,
                Categories = categoriesVm
            };

            return View(vm);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Contoso.Apps.SportsLeague/Views/Cart/Index.cshtml
@model Contoso.Apps.SportsLeague.Web.ViewModels.CartViewModel

@{
    ViewBag.Title = "Index";
}

@section HeaderOverlay {
    <div class="button-wrapper">
        <div class="container">
            <div class="row">
                <a href="#" class="btn-content">Shopping Cart</a>
            </div>
        </div>
    </div>
}

<section class="store">
    <div class="container">
        <div class="row">
            <div class="wrapper clearfix">

                @if (Model.CartItems.Count > 0)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>
                                    Product Name
                                </th>
                                <th>
                                    Price
                                </th>
                                <th>
                                    Quantity
                                </th>
                                <th>
                                    Total
                                </th>
                                @*<th></th>*@
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.CartItems)
                            {
                                <tr>
                                    <td>
                                        <img src="@Url.Content("~/Images/Products/")@item.ProductThumbnailPath" alt="@item.ProductProductName" class="center-block">
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Details", "Store", new { id = item.ProductId })">@Html.DisplayFor(modelItem => item.ProductProductName)</a>
                                    </td>
                                    <td>
                                        @String.Format("{0:c}", item.ProductUnitPrice)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Quantity)
                                    </td>
                                    <td>
                                        @String.Format("{0:c}", (item.ProductUnitPrice.HasValue ? Math.Round(item.ProductUnitPrice.Value * item.Quantity, 2) : 0))
                                    </td>
                                    @*<td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.ItemId }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.ItemId }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.ItemId })
                                        </td>*@
                                </tr>
                            }
                        </tbody>
                    </table>

                    <hr />

                    <div class="row">
                        <div class="col-xs-6 col-sm-8 col-md-10 col-lg-11 text-right text-warning"><strong># of Items:</strong></div>
                        <div class="col-xs-6 col-sm-4 col-md-2 col-lg-1 text-warning">@Model.ItemsTotal</div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-8 col-md-10 col-lg-11 text-right text-warning"><strong>Total:</strong></div>
                        <div class="col-xs-6 col-sm-4 col-md-2 col-lg-1 text-warning">@String.Format("{0:c}", Model.OrderTotal)</div>
                    </div>
                    
                    <div class="row">
                        <div class="col-sm-12">
                            &nbsp;
                        </div>
                    </div>

                    <div class="pull-right">
                        <a href="@Url.Action("Index", "Checkout")" class="btn btn-primary">Checkout</a>
                    </div>

                    <div class="pull-left">
                        <a href="@Url.Action("Index", "Store")" class="btn trans-btn"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;Keep shopping</a>
                    </div>
                }
                else
                {
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h3 class="panel-title">Your shopping cart is empty</h3>
                        </div>
                        <div class="panel-body">
                            <p>Oops! You haven't added anything to your shopping cart yet!</p>
                            <p>You may have forgotten to add something to the cart. How about <a href="@Url.Action("Index", "Store")" style="color: blue">you take another look</a> at our selection of awesome products to try again?</p>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</section>